ccid attempt at hosting ec2 w github action-runner part 8 :(

diff --git a/.github/workflows/cicd-workflow.yaml b/.github/workflows/cicd-workflow.yaml
--- a/.github/workflows/cicd-workflow.yaml
+++ b/.github/workflows/cicd-workflow.yaml
@@ -12,7 +12,7 @@ jobs:
         uses: actions/checkout@v3
       - name: Login to docker hub
         run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
-      - name: Build the docer image
+      - name: Build the docker image
         run: docker build -t jarai/slugmart .
       - name: Publish image to docker hub
         run: docker push jarai/slugmart:latest
@@ -21,9 +21,13 @@ jobs:
     needs: build 
     runs-on: aws-ec2
     steps:
-      - name: Pull image from docker
+      - name: Pull image from Docker Hub
         run: docker pull jarai/slugmart:latest
-      - name: Delete old container
-        run: docker rm -f slugmart-container
-      - name: Run docker container
-        run: docker run -d -p 3000:3000 --name slugmart-container jarai/slugmart
+      - name: Delete old container (if exists)
+        run: |
+          docker rm -f slugmart-container || echo "No existing container to remove"
+      - name: Run Docker container
+        run: |
+          docker run -d -p 3000:3000 --name slugmart-container jarai/slugmart || echo "Failed to start the container"
+      - name: Check running containers
+        run: docker ps
